static const char default_cfg[] =
"bind \"TAB\" \"+showscores\"\n"
"bind \"ENTER\" \"+jump\"\n"
"bind \"ESCAPE\" \"togglemenu\"\n"
"bind \"SPACE\" \"+jump\"\n"
"bind \"+\" \"sizeup\"\n"
"bind \",\" \"+moveleft\"\n"
"bind \"-\" \"sizedown\"\n"
"bind \".\" \"+moveright\"\n"
"bind \"/\" \"impulse 10\"\n"
"bind \"0\" \"impulse 0\"\n"
"bind \"1\" \"impulse 1\"\n"
"bind \"2\" \"impulse 2\"\n"
"bind \"3\" \"impulse 3\"\n"
"bind \"4\" \"impulse 4\"\n"
"bind \"5\" \"impulse 5\"\n"
"bind \"6\" \"impulse 6\"\n"
"bind \"7\" \"impulse 7\"\n"
"bind \"8\" \"impulse 8\"\n"
"bind \"9\" \"impulse 225\"\n"
"bind \"=\" \"sizeup\"\n"
"bind \"`\" \"toggleconsole\"\n"
"bind \"a\" \"+lookup\"\n"
"bind \"c\" \"+movedown\"\n"
"bind \"d\" \"+moveup\"\n"
"bind \"e\" \"+moveup\"\n"
"bind \"t\" \"messagemode\"\n"
"bind \"z\" \"+lookdown\"\n"
"bind \"~\" \"toggleconsole\"\n"
"bind \"PAUSE\" \"pause\"\n"
"bind \"UPARROW\" \"+forward\"\n"
"bind \"DOWNARROW\" \"+back\"\n"
"bind \"LEFTARROW\" \"impulse 12\"\n"
"bind \"RIGHTARROW\" \"impulse 10\"\n"
"bind \"ALT\" \"+strafe\"\n"
"bind \"CTRL\" \"+attack\"\n"
"bind \"SHIFT\" \"+speed\"\n"
"bind \"F1\" \"help\"\n"
"bind \"F2\" \"menu_save\"\n"
"bind \"F3\" \"menu_load\"\n"
"bind \"F4\" \"menu_options\"\n"
"bind \"F5\" \"menu_multiplayer\"\n"
"bind \"F6\" \"echo Quicksaving...; wait; save quick\"\n"
"bind \"F9\" \"echo Quickloading...; wait; load quick\"\n"
"bind \"F10\" \"quit\"\n"
"bind \"F11\" \"zoom_in\"\n"
"bind \"F12\" \"screenshot\"\n"
"bind \"INS\" \"+klook\"\n"
"bind \"DEL\" \"+lookdown\"\n"
"bind \"PGDN\" \"+lookup\"\n"
"bind \"END\" \"centerview\"\n"
"bind \"MOUSE1\" \"+attack\"\n"
"bind \"MOUSE2\" \"+forward\"\n"
"bind \"MOUSE3\" \"+mlook\"\n"
"bind \"TRIANGLE\" \"+forward\"\n"
"bind \"CIRCLE\" \"+moveright\"\n"
"bind \"CROSS\" \"+back\"\n"
"bind \"SQUARE\" \"+moveleft\"\n"
"bind \"LTRIGGER\" \"+jump\"\n"
"bind \"RTRIGGER\" \"+attack\"\n"
"_cl_color \"0\"\n"
"_cl_name \"player\"\n"
"_config_com_baud \"57600\"\n"
"_config_com_irq \"4\"\n"
"_config_com_modem \"1\"\n"
"_config_com_port \"0x3f8\"\n"
"_config_modem_clear \"ATZ\"\n"
"_config_modem_dialtype \"T\"\n"
"_config_modem_hangup \"AT H\"\n"
"_config_modem_init \"\"\n"
"_snd_mixahead \"0.1\"\n"
"acceleration \"1.0\"\n"
"accesspoint \"1\"\n"
"ambient_level \"0.3\"\n"
"bgmtype \"cd\"\n"
"bgmvolume \"1.000000\"\n"
"cl_autoaim \"0\"\n"
"cl_backspeed \"400.000000\"\n"
"cl_bob \"0.02\"\n"
"cl_bobcycle \"0.6\"\n"
"cl_bobside \"0.02\"\n"
"cl_bobsidecycle \"0.6\"\n"
"cl_bobsideup \"0.5\"\n"
"cl_bobup \"0.5\"\n"
"cl_confirmquit \"1\"\n"
"cl_crossx \"0\"\n"
"cl_crossy \"0\"\n"
"cl_forwardspeed \"400.000000\"\n"
"cl_rollspeed \"200\"\n"
"cl_sbar \"0.6\"\n"
"cl_sidespeed \"350\"\n"
"cl_upspeed \"200\"\n"
"crosshair \"1\"\n"
"gamma \"1.0\"\n"
"gl_keeptjunctions \"1\"\n"
"gl_subdivide_size \"128\"\n"
"in_analog_strafe \"0\"\n"
"in_disable_analog \"0\"\n"
"in_freelook_analog \"1\"\n"
"in_x_axis_adjust \"3\"\n"
"in_y_axis_adjust \"3\"\n"
"lookcenter \"1\"\n"
"lookspring \"0\"\n"
"lookstrafe \"0\"\n"
"m_forward \"1\"\n"
"m_pitch \"0.022\"\n"
"m_side \"0.8\"\n"
"m_yaw \"0.022\"\n"
"pq_drawfps \"1\"\n"
"pq_maxfps \"65\"\n"
"r_antialias \"0\"\n"
"r_dithering \"0\"\n"
"r_dynamic \"1\"\n"
"r_interpolate_animation \"1\"\n"
"r_interpolate_transform \"1\"\n"
"r_menufade \"0.5\"\n"
"r_mipmaps \"1\"\n"
"r_mipmaps_bias \"-7\"\n"
"r_mipmaps_func \"2\"\n"
"r_model_brightness \"1\"\n"
"r_model_contrast \"0\"\n"
"r_particles_simple \"0\"\n"
"r_skybox \"1\"\n"
"r_skyclip \"2560\"\n"
"r_skyfog \"1\"\n"
"r_tex_scale_down \"0\"\n"
"r_truegunangle \"0\"\n"
"r_viewmodeloffset \"0\"\n"
"r_vsync \"0\"\n"
"saved1 \"0\"\n"
"saved2 \"0\"\n"
"saved3 \"0\"\n"
"saved4 \"0\"\n"
"savedgamecfg \"0\"\n"
"savegame_compatibility \"0\"\n"
"scr_loadscreen \"1\"\n"
"sensitivity \"33\"\n"
"tolerance \"0.25\"\n"
"v_centermove \"1\"\n"
"v_centerspeed \"100\"\n"
"v_gunkick \"0\"\n"
"v_kickpitch \"0.6\"\n"
"v_kickroll \"0.6\"\n"
"v_kicktime \"0.5\"\n"
"viewsize \"110\"\n"
"vl_highcut \"128\"\n"
"vl_light \"0\"\n"
"vl_lowcut \"60\"\n"
"vl_pitch \"45\"\n"
"vl_yaw \"45\"\n"
"volume \"0.7\"\n";